namespace GarrysModLuaShared.Enums
{
    public enum CREATERENDERTARGETFLAGS
    {
        CREATERENDERTARGETFLAGS_AUTOMIPMAP = 2,
        CREATERENDERTARGETFLAGS_HDR = 1,
        CREATERENDERTARGETFLAGS_UNFILTERABLE_OK = 4
    }
}