namespace GarrysModLuaShared.Enums
{
    public enum SENSORBONE
    {
        SENSORBONE_SHOULDER_RIGHT = 8,
        SENSORBONE_SHOULDER_LEFT = 4,
        SENSORBONE_HIP = 0,
        SENSORBONE_ELBOW_RIGHT = 9,
        SENSORBONE_KNEE_RIGHT = 17,
        SENSORBONE_WRIST_RIGHT = 10,
        SENSORBONE_ANKLE_LEFT = 14,
        SENSORBONE_FOOT_LEFT = 15,
        SENSORBONE_WRIST_LEFT = 6,
        SENSORBONE_FOOT_RIGHT = 19,
        SENSORBONE_HAND_RIGHT = 11,
        SENSORBONE_SHOULDER = 2,
        SENSORBONE_HIP_LEFT = 12,
        SENSORBONE_HIP_RIGHT = 16,
        SENSORBONE_HAND_LEFT = 7,
        SENSORBONE_ANKLE_RIGHT = 18,
        SENSORBONE_SPINE = 1,
        SENSORBONE_ELBOW_LEFT = 5,
        SENSORBONE_KNEE_LEFT = 13,
        SENSORBONE_HEAD = 3
    }
}