namespace GarrysModLuaShared.Enums
{
    public enum STUDIO : long
    {
        STUDIO_DRAWTRANSLUCENTSUBMODELS = 4,
        STUDIO_GENERATE_STATS = 16777216,
        STUDIO_ITEM_BLINK = 64,
        STUDIO_NOSHADOWS = 128,
        STUDIO_RENDER = 1,
        STUDIO_SHADOWDEPTHTEXTURE = 1073741824,
        STUDIO_SSAODEPTHTEXTURE = 134217728,
        STUDIO_STATIC_LIGHTING = 16,
        STUDIO_TRANSPARENCY = 2147483648,
        STUDIO_TWOPASS = 8,
        STUDIO_VIEWXFORMATTACHMENTS = 2,
        STUDIO_WIREFRAME = 32,
        STUDIO_WIREFRAME_VCOLLIDE = 256
    }
}